package com.game.contraband.infrastructure.websocket.message;

public enum ExceptionCode {
    UNKNOWN_ERROR,

    CHAT_MESSAGE_EMPTY,
    CHAT_USER_BLOCKED,

    GAME_INVALID_STATE,

    NOT_CURRENT_ROUND_INSPECTOR,
    NOT_CURRENT_ROUND_SMUGGLER,

    LOBBY_FULL,
    LOBBY_MAX_PLAYER_CHANGE_FORBIDDEN,
    LOBBY_INVALID_OPERATION,
    LOBBY_TEAM_BALANCE_REQUIRED,
    LOBBY_READY_STATE_TEAM_CHANGE_FORBIDDEN,

    GAME_ROOM_NOT_FOUND
}
