package com.game.contraband.infrastructure.websocket.message;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Optional;

public enum WebSocketOutboundMessageType {

    WS_HEALTH_PING("WS_HEALTH_PING"),
    WS_RECONNECT("WS_RECONNECT"),
    HEARTBEAT_PING("PING"),
    HEARTBEAT_PONG("PONG"),
    SESSION_HEALTH_PONG("WS_PONG"),
    EXCEPTION_MESSAGE("EXCEPTION_MESSAGE"),

    ROOM_DIRECTORY_UPDATED("ROOM_DIRECTORY_UPDATED"),

    CHAT_WELCOME("CHAT_WELCOME"),
    LOBBY_CHAT_MESSAGE("LOBBY_CHAT_MESSAGE"),
    CHAT_LEFT("CHAT_LEFT"),
    CHAT_KICKED("CHAT_KICKED"),
    CHAT_MESSAGE_MASKED("CHAT_MESSAGE_MASKED"),

    SMUGGLER_TEAM_CHAT_MESSAGE("SMUGGLER_TEAM_CHAT_MESSAGE"),
    INSPECTOR_TEAM_CHAT_MESSAGE("INSPECTOR_TEAM_CHAT_MESSAGE"),
    ROUND_CHAT_MESSAGE("ROUND_CHAT_MESSAGE"),

    START_GAME("START_GAME"),
    ROUND_SELECTION_TIMER("ROUND_SELECTION_TIMER"),
    REGISTERED_SMUGGLER_ID("REGISTERED_SMUGGLER_ID"),
    FIXED_SMUGGLER_ID("FIXED_SMUGGLER_ID"),
    REGISTERED_INSPECTOR_ID("REGISTERED_INSPECTOR_ID"),
    FIXED_SMUGGLER_ID_FOR_INSPECTOR("FIXED_SMUGGLER_ID_FOR_INSPECTOR"),
    FIXED_INSPECTOR_ID("FIXED_INSPECTOR_ID"),
    FIXED_INSPECTOR_ID_FOR_SMUGGLER("FIXED_INSPECTOR_ID_FOR_SMUGGLER"),
    SMUGGLER_APPROVAL_STATE("SMUGGLER_APPROVAL_STATE"),
    INSPECTOR_APPROVAL_STATE("INSPECTOR_APPROVAL_STATE"),

    START_NEW_ROUND("START_NEW_ROUND"),
    FINISHED_ROUND("FINISHED_ROUND"),
    FINISHED_GAME("FINISHED_GAME"),
    TRANSFER_FAILED("TRANSFER_FAILED"),
    DECIDED_INSPECTOR_BEHAVIOR_FOR_SMUGGLER_TEAM("DECIDED_INSPECTOR_BEHAVIOR_FOR_SMUGGLER_TEAM"),
    DECIDED_PASS("DECIDED_PASS"),
    DECIDED_INSPECTION("DECIDED_INSPECTION"),
    DECIDED_SMUGGLER_AMOUNT_FOR_SMUGGLER_TEAM("DECIDED_SMUGGLER_AMOUNT_FOR_SMUGGLER_TEAM"),
    DECIDED_SMUGGLER_AMOUNT_FOR_INSPECTOR_TEAM("DECIDED_SMUGGLER_AMOUNT_FOR_INSPECTOR_TEAM"),
    TRANSFER("TRANSFER");

    private final String type;

    WebSocketOutboundMessageType(String type) {
        this.type = type;
    }

    @JsonValue
    public String type() {
        return type;
    }

    public boolean isSameType(String rawType) {
        return type.equalsIgnoreCase(rawType);
    }

    public static Optional<WebSocketOutboundMessageType> from(String rawType) {
        return Arrays.stream(values())
                     .filter(value -> value.isSameType(rawType))
                     .findFirst();
    }
}
